{{- if and (hasKey .Values "agent") (hasKey .Values.agent "clusterToken")
}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ with .Values }}{{ with .agent }}{{ with .tokenSecret }}{{ . }}{{- else -}}"cluster-token"{{- end }}{{- else -}}"cluster-token"{{- end }}{{- else -}}"cluster-token"{{- end }}
  namespace: signadot
data:
  token: {{ .Values.controlPlane.clusterToken | b64enc | quote }}
{{- end }}
