{{- if and (hasKey .Values "controlPlane") (hasKey .Values.controlPlane "clusterToken")
}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ with .Values }}{{ with .controlPlane }}{{ with .tokenSecret }}{{ . }}{{- else -}}"cluster-token"{{- end }}{{- else -}}"cluster-token"{{- end }}{{- else -}}"cluster-token"{{- end }}
  namespace: signadot
data:
  token: {{ .Values.controlPlane.clusterToken | b64enc | quote }}
{{- end }}
