{{- if and (hasKey .Values "agent") (hasKey .Values.agent "clusterToken")
}}
apiVersion: v1
kind: Secret
metadata:
  name: cluster-agent
  namespace: signadot
data:
  token: {{ .Values.agent.clusterToken | b64enc | quote }}
{{- end }}
