{{ if ne (include "valuesDefaultStr" (list .Values "previewServer" "enabled") | trim) "false" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    {{- range $key, $val := .Values.commonAnnotations }}
    {{ $key | quote }}: {{ $val | quote }}
    {{- end }}
  labels:
    {{- range $key, $val := .Values.commonLabels }}
    {{ $key | quote }}: {{ $val | quote }}
    {{- end }}
  name: previewserver
  namespace: signadot
spec:
  replicas:
    {{- include "valuesDefault" (list .Values 1 "previewServer" "replicas") | trim | printf " %s" }}
  selector:
    matchLabels:
      app: previewserver
  template:
    metadata:
      annotations:
        {{- range $key, $val := .Values.commonAnnotations }}
        {{ $key | quote }}: {{ $val | quote }}
        {{- end }}
        {{- range $key, $val := .Values.podAnnotations }}
        {{ $key | quote }}: {{ $val | quote }}
        {{- end }}
        {{- if and (hasKey .Values "linkerd") (hasKey .Values.linkerd "enabled") .Values.linkerd.enabled }}
        {{- if and (hasKey .Values.linkerd "operator") (hasKey .Values.linkerd.operator "podAnnotations") .Values.linkerd.operator.podAnnotations }}
        {{- range $key, $val := .Values.linkerd.operator.podAnnotations }}
        {{ $key | quote }}: {{ $val | quote }}
        {{- end }}
        {{- else }}
        linkerd.io/inject: "enabled"
        {{- end }}
        {{- end }}
        cluster-config-checksum: '{{ include (print $.Template.BasePath "/cluster-config-configmap.yaml") . | sha256sum }}'
      labels:
        {{- range $key, $val := .Values.commonLabels }}
        {{ $key | quote }}: {{ $val | quote }}
        {{- end }}
        {{- range $key, $val := .Values.podLabels }}
        {{ $key | quote }}: {{ $val | quote }}
        {{- end }}
        {{- if and (hasKey .Values "istio") (hasKey .Values.istio "enabled") .Values.istio.enabled }}
        {{- if and (hasKey .Values.istio "operator") (hasKey .Values.istio.operator "podLabels") .Values.istio.operator.podLabels }}
        {{- range $key, $val := .Values.istio.operator.podLabels }}
        {{ $key | quote }}: {{ $val | quote }}
        {{- end }}
        {{- else }}
        sidecar.istio.io/inject: "true"
        {{- end }}
        {{- end }}
        app: previewserver
    spec:
      affinity:
        nodeAffinity:
          {{- $na := include "valuesDefault" (list .Values "" "previewServer" "nodeAffinity") }}{{- if $na }}
          {{- $na | nindent 10 }}
          {{- else }} {}{{- end }}
      containers:
      - env:
        - name: LOG_LEVEL
          value: |-
            {{ include "valuesDefaultStr" (list .Values "previewServer" "logLevel") }}
        image: |-
          {{ include "operatorImage" (list .Values "" "signadot" "v1.4.0" "previewserver" "previewServer") }}
        imagePullPolicy: |-
          {{ include "valuesDefault" (list .Values "IfNotPresent" "previewServer" "imagePullPolicy") }}
        name: previewserver
        ports:
        - containerPort: 8080
          name: preview
        - containerPort: 16001
          name: healthz
        readinessProbe:
          httpGet:
            path: /healthz
            port: 16001
        resources:
          {{- $r := include "valuesDefault" (list .Values "" "previewServer" "resources") }}{{- if $r }}
          {{- $r | nindent 10 }}
          {{- else }}
          limits:
            memory: 1Gi
          requests:
            memory: 128Mi
          {{- end }}
        volumeMounts:
        - name: signadot-config
          mountPath: /etc/signadot/
          readOnly: true
      imagePullSecrets:
        {{- if .Values.imagePullSecrets }}
        {{- range .Values.imagePullSecrets }}
        - name: {{ . }}
        {{- end }}
        {{- else }} []{{- end }}
      serviceAccountName: previewserver
      tolerations:
        {{- $t := include "valuesDefault" (list .Values "" "previewServer" "tolerations") }}{{- if $t }}
        {{- $t | nindent 8 }}
        {{- else }} []{{- end }}
      volumes:
      - name: signadot-config
        projected:
          sources:
          - configMap:
              name: cluster-config
              items:
              - key: cluster_config.yaml
                path: cluster_config.yaml
{{ end }}
# This file is generated. Do not edit.
